name: Waterflow CI
on: [push]		
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.12
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run MLFlow ui
        run: uv run mlflow ui &
      - name: Run tests
        run: uv run pytest 
      