name: Waterflow CI
on: [push]		
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.12
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Start MLflow server
        run: |
          uv run mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 127.0.0.1 --port 5000 &
          sleep 5
      - name: Run registry models
        run: uv run python waterflow/ops/registry_models.py
      - name: Run tests
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: uv run pytest 